"""added columns to productions

Revision ID: a8981a77065e
Revises: 7d54874d8b9a
Create Date: 2023-05-24 11:11:11.031885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8981a77065e'
down_revision = '7d54874d8b9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('budget', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('director', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ongoing', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productions', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('ongoing')
        batch_op.drop_column('description')
        batch_op.drop_column('director')
        batch_op.drop_column('image')
        batch_op.drop_column('budget')
        batch_op.drop_column('genre')

    # ### end Alembic commands ###
